name: Bug Report
description: Report a bug / crash
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        To help us help you, please provide as much information as you can, this helps us with debugging and reproducing the issue.
  - type: input
    id: version
    attributes:
      label: Mod version
      description: |
        You can find the version of the mod in the mods file name or in-game in the mods button on the main menu.
      placeholder: 1.0.0
    validations:
      required: true
  - type: input
    id: mc-version
    attributes:
      label: Minecraft Version
      placeholder: 26.1.2
    validations:
      required: true
  - type: input
    id: modpack
    attributes:
      label: Modpack & Version
      description: |
        If you are running a Modpack, please provide the name and version of the pack.
      placeholder: Direwolf20 - 1.16 (2.4)
    validations:
      required: false
  - type: dropdown
    id: optifine
    validations:
      required: true
    attributes:
      label: Do you have optifine/shaders installed?
      description: |
        If you have a different rendering mod installed, please add to in the extra info box at the end.
      multiple: false
      options:
        - 'Yes'
        - 'No'
        - 'I have other rendering based mods installed'
  - type: textarea
    id: bugdesc
    attributes:
      label: Describe the issue
      description: |
        A clear and concise description of what the bug is
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Tell us how we can reproduce the issue
      placeholder: |
        1. Open Mc...
        2. Do...
        3. See error...
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Log files
      description: "Link(s) to any log files that you can provide, typically, /logs/debug.log and /logs/latest.log, we recommend using [Gist](https://gist.github.com/) or [Pastebin](https://pastebin.com/) to share the logs."
      placeholder: |
        If you do not have any logs, please enter `N/A` but note that this is very rare that you will have a bug and not have any logs.
    validations:
      required: true
