name: Build

on:
  push:
    branches:
      - master
      - mc/*
  pull_request:
    branches:
      - master

jobs:
  build:
    if: |
      !contains(github.event.head_commit.message, '[ciskip]')
    uses: ./.github/workflows/base.yaml
    with:
      gradle-tasks: 'build'
